### ISSUE TITLE
pgsql arrays

### ISSUE THREAD

**Issue by c0de9en** [openresty/rds-json-nginx-module#5]
I have a table with ARRAY field:
CREATE TABLE usr (
  name          TEXT    NOT NULL PRIMARY KEY
, pw            TEXT    NOT NULL DEFAULT (floor(random() \* 10000000000))::TEXT
, phone         INT8[]  NOT NULL DEFAULT '{}'
);

pgsql exports it in json correct:
SELECT row_to_json(u.*) FROM (  SELECT name, phone FROM usr WHERE name = 'user1') AS u;
                  row_to_json  
{"name":"dsp","phone":[1234567890,3243546576]}

but rds-json gave me incorrect json:
{"name":"dsp","phone":"{1234567890,3243546576}"}

Is it possible to export arrays as json arrays?

**Comment by msva** [comment]
@agentzh I don't know if my issue is similar to this, but when I using rds_json with tables containing "json"-type columns, they going to string too (while I expect rds_json to just append that as is, but not as a string).

**Comment by agentzh** [comment]
@msva Yes, this is the current behaviour. I'm not sure if we should parse the stringified values from the database ourselves in the client diver.
